version: '3'
services:
  site1:
    image: nginx:latest
    container_name: site1
    ports:
      - "8082:80"
    volumes:
      - ./site1:/usr/share/nginx/html:ro

  site2:
    image: nginx:latest
    container_name: site2
    ports:
      - "8083:80"
    volumes:
      - ./site2:/usr/share/nginx/html:ro

  site3:
    image: nginx:latest
    container_name: site3
    ports:
      - "8084:80"
    volumes:
      - ./site3:/usr/share/nginx/html:ro
