name: Deploy Static Sites to EC2 with Docker Compose

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/static-sites/

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo "Ensuring Docker is running..."
            sudo systemctl start docker
            sudo systemctl enable docker

            # Extend docker compose timeout
            export COMPOSE_HTTP_TIMEOUT=300

            cd /home/${USER}/static-sites

            echo "Stopping old containers..."
            sudo docker compose down || true

            echo "Pulling latest images..."
            sudo docker compose pull

            echo "Starting containers..."
            sudo docker compose up -d --build
          EOF
